# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import laneq_pb2 as laneq__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in laneq_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LaneqStub:
    """Laneq service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Push = channel.unary_unary(
                '/laneq.v1.Laneq/Push',
                request_serializer=laneq__pb2.PushRequest.SerializeToString,
                response_deserializer=laneq__pb2.PushResponse.FromString,
                _registered_method=True)
        self.Take = channel.unary_unary(
                '/laneq.v1.Laneq/Take',
                request_serializer=laneq__pb2.TakeRequest.SerializeToString,
                response_deserializer=laneq__pb2.TakeResponse.FromString,
                _registered_method=True)
        self.Peek = channel.unary_unary(
                '/laneq.v1.Laneq/Peek',
                request_serializer=laneq__pb2.PeekRequest.SerializeToString,
                response_deserializer=laneq__pb2.PeekResponse.FromString,
                _registered_method=True)
        self.Show = channel.unary_unary(
                '/laneq.v1.Laneq/Show',
                request_serializer=laneq__pb2.ShowRequest.SerializeToString,
                response_deserializer=laneq__pb2.ShowResponse.FromString,
                _registered_method=True)
        self.Listing = channel.unary_unary(
                '/laneq.v1.Laneq/Listing',
                request_serializer=laneq__pb2.ListingRequest.SerializeToString,
                response_deserializer=laneq__pb2.ListingResponse.FromString,
                _registered_method=True)
        self.Reprioritize = channel.unary_unary(
                '/laneq.v1.Laneq/Reprioritize',
                request_serializer=laneq__pb2.ReprioritizeRequest.SerializeToString,
                response_deserializer=laneq__pb2.ReprioritizeResponse.FromString,
                _registered_method=True)
        self.SetStatus = channel.unary_unary(
                '/laneq.v1.Laneq/SetStatus',
                request_serializer=laneq__pb2.SetStatusRequest.SerializeToString,
                response_deserializer=laneq__pb2.SetStatusResponse.FromString,
                _registered_method=True)
        self.Defer = channel.unary_unary(
                '/laneq.v1.Laneq/Defer',
                request_serializer=laneq__pb2.DeferRequest.SerializeToString,
                response_deserializer=laneq__pb2.DeferResponse.FromString,
                _registered_method=True)
        self.Touch = channel.unary_unary(
                '/laneq.v1.Laneq/Touch',
                request_serializer=laneq__pb2.TouchRequest.SerializeToString,
                response_deserializer=laneq__pb2.TouchResponse.FromString,
                _registered_method=True)
        self.Reap = channel.unary_unary(
                '/laneq.v1.Laneq/Reap',
                request_serializer=laneq__pb2.ReapRequest.SerializeToString,
                response_deserializer=laneq__pb2.ReapResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/laneq.v1.Laneq/Stats',
                request_serializer=laneq__pb2.StatsRequest.SerializeToString,
                response_deserializer=laneq__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.ThreadStatus = channel.unary_unary(
                '/laneq.v1.Laneq/ThreadStatus',
                request_serializer=laneq__pb2.ThreadStatusRequest.SerializeToString,
                response_deserializer=laneq__pb2.ThreadStatusResponse.FromString,
                _registered_method=True)
        self.Park = channel.unary_unary(
                '/laneq.v1.Laneq/Park',
                request_serializer=laneq__pb2.ParkRequest.SerializeToString,
                response_deserializer=laneq__pb2.ParkResponse.FromString,
                _registered_method=True)
        self.Unpark = channel.unary_unary(
                '/laneq.v1.Laneq/Unpark',
                request_serializer=laneq__pb2.UnparkRequest.SerializeToString,
                response_deserializer=laneq__pb2.UnparkResponse.FromString,
                _registered_method=True)


class LaneqServicer:
    """Laneq service definition.
    """

    def Push(self, request, context):
        """Push enqueues a new directive with the specified priority and lane.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Take(self, request, context):
        """Take atomically claims the highest-priority eligible pending directive.
        Returns an empty Directive if no eligible directive exists.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Peek(self, request, context):
        """Peek returns the next eligible directive without claiming it.
        Returns an empty Directive if no eligible directive exists.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Show(self, request, context):
        """Show retrieves full details of a directive by ID, including its thread.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Listing(self, request, context):
        """Listing queries directives with optional filters (status, lane, thread).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reprioritize(self, request, context):
        """Reprioritize changes a directive's priority.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStatus(self, request, context):
        """SetStatus changes a directive's status (pending, done, dropped).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Defer(self, request, context):
        """Defer defers a directive until a specified time or delay, optionally blocking on dependencies.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Touch(self, request, context):
        """Touch renews the lease on a claimed directive.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reap(self, request, context):
        """Reap reclaims expired leases and stale deferred directives.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Stats returns queue statistics (counts by status, consumer activity).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ThreadStatus(self, request, context):
        """ThreadStatus queries the status of a directive thread (parent + children).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Park(self, request, context):
        """Park moves a claimed directive into durable hold (excluded from claim/peek/reap).
        Must be called with a valid lease (consumer + active lease_until).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unpark(self, request, context):
        """Unpark removes a directive from parked status (returns to pending).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LaneqServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Push': grpc.unary_unary_rpc_method_handler(
                    servicer.Push,
                    request_deserializer=laneq__pb2.PushRequest.FromString,
                    response_serializer=laneq__pb2.PushResponse.SerializeToString,
            ),
            'Take': grpc.unary_unary_rpc_method_handler(
                    servicer.Take,
                    request_deserializer=laneq__pb2.TakeRequest.FromString,
                    response_serializer=laneq__pb2.TakeResponse.SerializeToString,
            ),
            'Peek': grpc.unary_unary_rpc_method_handler(
                    servicer.Peek,
                    request_deserializer=laneq__pb2.PeekRequest.FromString,
                    response_serializer=laneq__pb2.PeekResponse.SerializeToString,
            ),
            'Show': grpc.unary_unary_rpc_method_handler(
                    servicer.Show,
                    request_deserializer=laneq__pb2.ShowRequest.FromString,
                    response_serializer=laneq__pb2.ShowResponse.SerializeToString,
            ),
            'Listing': grpc.unary_unary_rpc_method_handler(
                    servicer.Listing,
                    request_deserializer=laneq__pb2.ListingRequest.FromString,
                    response_serializer=laneq__pb2.ListingResponse.SerializeToString,
            ),
            'Reprioritize': grpc.unary_unary_rpc_method_handler(
                    servicer.Reprioritize,
                    request_deserializer=laneq__pb2.ReprioritizeRequest.FromString,
                    response_serializer=laneq__pb2.ReprioritizeResponse.SerializeToString,
            ),
            'SetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStatus,
                    request_deserializer=laneq__pb2.SetStatusRequest.FromString,
                    response_serializer=laneq__pb2.SetStatusResponse.SerializeToString,
            ),
            'Defer': grpc.unary_unary_rpc_method_handler(
                    servicer.Defer,
                    request_deserializer=laneq__pb2.DeferRequest.FromString,
                    response_serializer=laneq__pb2.DeferResponse.SerializeToString,
            ),
            'Touch': grpc.unary_unary_rpc_method_handler(
                    servicer.Touch,
                    request_deserializer=laneq__pb2.TouchRequest.FromString,
                    response_serializer=laneq__pb2.TouchResponse.SerializeToString,
            ),
            'Reap': grpc.unary_unary_rpc_method_handler(
                    servicer.Reap,
                    request_deserializer=laneq__pb2.ReapRequest.FromString,
                    response_serializer=laneq__pb2.ReapResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=laneq__pb2.StatsRequest.FromString,
                    response_serializer=laneq__pb2.StatsResponse.SerializeToString,
            ),
            'ThreadStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ThreadStatus,
                    request_deserializer=laneq__pb2.ThreadStatusRequest.FromString,
                    response_serializer=laneq__pb2.ThreadStatusResponse.SerializeToString,
            ),
            'Park': grpc.unary_unary_rpc_method_handler(
                    servicer.Park,
                    request_deserializer=laneq__pb2.ParkRequest.FromString,
                    response_serializer=laneq__pb2.ParkResponse.SerializeToString,
            ),
            'Unpark': grpc.unary_unary_rpc_method_handler(
                    servicer.Unpark,
                    request_deserializer=laneq__pb2.UnparkRequest.FromString,
                    response_serializer=laneq__pb2.UnparkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'laneq.v1.Laneq', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('laneq.v1.Laneq', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Laneq:
    """Laneq service definition.
    """

    @staticmethod
    def Push(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laneq.v1.Laneq/Push',
            laneq__pb2.PushRequest.SerializeToString,
            laneq__pb2.PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Take(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laneq.v1.Laneq/Take',
            laneq__pb2.TakeRequest.SerializeToString,
            laneq__pb2.TakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Peek(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laneq.v1.Laneq/Peek',
            laneq__pb2.PeekRequest.SerializeToString,
            laneq__pb2.PeekResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Show(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laneq.v1.Laneq/Show',
            laneq__pb2.ShowRequest.SerializeToString,
            laneq__pb2.ShowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Listing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laneq.v1.Laneq/Listing',
            laneq__pb2.ListingRequest.SerializeToString,
            laneq__pb2.ListingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reprioritize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laneq.v1.Laneq/Reprioritize',
            laneq__pb2.ReprioritizeRequest.SerializeToString,
            laneq__pb2.ReprioritizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laneq.v1.Laneq/SetStatus',
            laneq__pb2.SetStatusRequest.SerializeToString,
            laneq__pb2.SetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Defer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laneq.v1.Laneq/Defer',
            laneq__pb2.DeferRequest.SerializeToString,
            laneq__pb2.DeferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Touch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laneq.v1.Laneq/Touch',
            laneq__pb2.TouchRequest.SerializeToString,
            laneq__pb2.TouchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laneq.v1.Laneq/Reap',
            laneq__pb2.ReapRequest.SerializeToString,
            laneq__pb2.ReapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laneq.v1.Laneq/Stats',
            laneq__pb2.StatsRequest.SerializeToString,
            laneq__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ThreadStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laneq.v1.Laneq/ThreadStatus',
            laneq__pb2.ThreadStatusRequest.SerializeToString,
            laneq__pb2.ThreadStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Park(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laneq.v1.Laneq/Park',
            laneq__pb2.ParkRequest.SerializeToString,
            laneq__pb2.ParkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unpark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laneq.v1.Laneq/Unpark',
            laneq__pb2.UnparkRequest.SerializeToString,
            laneq__pb2.UnparkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
