name: Buf Format Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  buf-format-check:
    uses: selamy-labs/.github/.github/workflows/buf-format-check.yml@main
    with:
      input: proto
